spring.application.name=Trip

spring.h2.console.enabled=true
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:./DBTrip;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.resolve-lazily=true

server.max-http-request-header-size=1024KB

spring.ai.google.genai.api-key=${GEMINI_KEY:}
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
spring.ai.retry.max-attempts=2
spring.ai.retry.initial-interval=1000
spring.ai.retry.multiplier=2.0

spring.jpa.open-in-view=false

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.mvc.async.request-timeout=-1

server.tomcat.connection-timeout=600000

spring.security.strategy=MODE_INHERITABLETHREADLOCAL

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.okhttp3=DEBUG
logging.level.root=INFO
logging.level.com.google=TRACE

ors.api.key=${ORS_API_KEY:}
ors.base.url=https://api.openrouteservice.org/v2/directions




jwt.secret=${JWT_SECRET:}


app.admin.email=${ADMIN_EMAIL:}
app.admin.password=${ADMIN_PASSWORD:}


app.env=${APP_ENV:}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,email,profile


app.frontend.url=${FRONTEND_URL:}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true